// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kndsxrzdxrgdtjixkwue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuZHN4cnpkeHJnZHRqaXhrd3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTUxMzEsImV4cCI6MjA2OTA3MTEzMX0.aAwwnNubZCwCo5JDpBxkJIIzmpD2ioql5vPmIRwTo_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});